apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: {{PROJECT_NAME}}

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  app: {{PROJECT_NAME}}
  managed-by: oneclickops
