apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{PROJECT_NAME}}
  labels:
    app: {{PROJECT_NAME}}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{PROJECT_NAME}}
